# Build-number preparation and commit helper.
#
# Rule:
#   - The counter stores the last successfully linked build number.
#   - PREPARE generates counter + 1 without changing the counter file.
#   - COMMIT writes the prepared number only after the executable links.
#   - It RESETS to 1 when the major.minor changes (e.g. 3.0.x → 3.1.0).
#   - A patch bump (3.0.0 → 3.0.1) does NOT reset it.
# The counter file stores "<major>.<minor>:<number>".
#
# Args:
#   -DMODE=PREPARE|COMMIT -DVERSION=<x.y.z> -DOUT=<version_build.cpp>
#   -DOUTHDR=<version_build.h> -DCOUNTER=<counter file> -DPENDING=<pending file>
#   -P bump_build.cmake
#
# OUTHDR receives the same number as plain macros so the Windows VERSIONINFO
# resources report exactly the build the executable prints in its banner.
if(NOT DEFINED VERSION)
  set(VERSION "0.0.0")
endif()
if(NOT DEFINED MODE)
  set(MODE "PREPARE")
endif()
if(NOT DEFINED PENDING)
  set(PENDING "${OUT}.pending")
endif()

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)" _ignore "${VERSION}")
set(KEY "${CMAKE_MATCH_1}.${CMAKE_MATCH_2}")

if(MODE STREQUAL "PREPARE")
  set(NUM 1)
  if(EXISTS "${COUNTER}")
    file(READ "${COUNTER}" _c)
    string(STRIP "${_c}" _c)
    if(_c MATCHES "^([0-9]+\\.[0-9]+):([0-9]+)$")
      if("${CMAKE_MATCH_1}" STREQUAL "${KEY}")
        math(EXPR NUM "${CMAKE_MATCH_2} + 1")
      endif()
    endif()
  endif()

  string(TIMESTAMP TS "%Y-%m-%d %H:%M:%S")
  file(WRITE "${OUT}"
    "#include \"common/version.h\"\n\nnamespace dice {\n\nint buildNumber() { return ${NUM}; }\nstd::string buildTime() { return \"${TS}\"; }\n\n}  // namespace dice\n")
  file(WRITE "${PENDING}" "${KEY}:${NUM}\n")

  if(DEFINED OUTHDR)
    string(REGEX MATCH "^([0-9]+)\.([0-9]+)\.([0-9]+)" _ignore "${VERSION}")
    set(V_MAJOR "${CMAKE_MATCH_1}")
    set(V_MINOR "${CMAKE_MATCH_2}")
    set(V_PATCH "${CMAKE_MATCH_3}")
    file(WRITE "${OUTHDR}"
      "// Generated by bump_build.cmake. Do not edit.\n"
      "#pragma once\n\n"
      "#define DICE_VER_MAJOR ${V_MAJOR}\n"
      "#define DICE_VER_MINOR ${V_MINOR}\n"
      "#define DICE_VER_PATCH ${V_PATCH}\n"
      "#define DICE_VER_BUILD ${NUM}\n"
      "#define DICE_VER_STRING \"${V_MAJOR}.${V_MINOR}.${V_PATCH}.${NUM}\"\n"
      "#define DICE_PRODUCT_VERSION_STRING \"${VERSION} (build ${NUM})\"\n")
  endif()
elseif(MODE STREQUAL "COMMIT")
  if(NOT EXISTS "${PENDING}")
    message(FATAL_ERROR "Missing pending build number: ${PENDING}")
  endif()
  file(READ "${PENDING}" _pending)
  string(STRIP "${_pending}" _pending)
  if(NOT _pending MATCHES "^${KEY}:([0-9]+)$")
    message(FATAL_ERROR "Invalid pending build number: ${_pending}")
  endif()
  file(WRITE "${COUNTER}" "${_pending}\n")
  file(REMOVE "${PENDING}")
else()
  message(FATAL_ERROR "Unsupported build-number mode: ${MODE}")
endif()
